import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css"; // globals.css에서 색상을 관리

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",  // 폰트 경로 주석 처리
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} antialiased`} // 폰트 관련 클래스 주석 처리
        className="antialiased text-font-color" // 폰트 관련 클래스 
        
      >
        {children}
      </body>
    </html>
  );
}
